# -*- coding: utf-8 -*-
"""requests.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n93EOq4-9lfRKHkJ6l_cxas35oVY83Q0
"""

import requests 
import json
import pandas as pd

link = "https://economia.awesomeapi.com.br/last/USD-BRL,EUR-BRL,BTC-BRL"
req = requests.get(link)

print(req.json())

with open('data.json', 'w') as fp:
  json.dump(req.json(), fp)

with open('data.json', 'r') as fp:
    data = json.load(fp)
print(data)
print(type(data))